# https://neptune.ai

neptune:
  _target_: lightning.pytorch.loggers.neptune.NeptuneLogger
  api_key: ${oc.env:NEPTUNE_API_TOKEN} # api key is loaded from environment variable
  project: michal.budnik1997/contact-pdb
  # name: ""
  log_model_checkpoints: False
  prefix: ""
